### PR TITLE
Feature/smart state

### LINKED ISSUE #912: Sanity check of robot smach states
It's desirable to check for available (robot) parts and methods within parts on construction of the statemachine. This might catch many bugs before they happen in practice (already during programming, simulating). 

A suggestion is to use [AST](https://docs.python.org/3/library/ast.html) to parse the execute method and inspect which robot parts and attributes of these parts are required.

Some questions:
* Do or don't we want to fork smach?
* How can we enforce the use of a parameter check. Adding it to the `__init__` is not convenient: that would mean that `super` needs to be called at the *end* of the `__init__` of the deriving class. Using a separate method is hard to enforce. The following snipped might provide some inspiration:
```python
class smach.State(...):
    def __init__(...):
        self._is_checked = False

    def check_attributes(self):
        ....
        self._is_checked = True

    @property
    def is_checked(self):
        return self._is_checked


class smach.StateMachine(...):
    def add(self, state):
        assert(state.is_checked, "Attributes of {} have not been checked, did you call 'check_attributes'?")
```

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Provides the following check on construction of a statemachine:
- Checks if all member variables of a state and their attribute exist. This also prevents adding member variables outside the constructor, as they will not be available at the time of the test, so an AssertionError will be raised.
- For all calls to member functions of the state and its member variables, it is checked if it is callable. (No argument tests yet, see #1)

Please check code for:
- bugs
- efficiency
- location of all the code (Maybe some stuff should be move to a separate file?)

This fixes tue-robotics/tue_robocup#912

### CODE REVIEW

**Review by jlunenburg — CHANGES_REQUESTED** [review]
* Add tests
* Move code to separate file
* Add docstrings where necessary
* Make sure no code is duplicated

**Review by jlunenburg — COMMENTED** [review]
Het ziet er netjes uit. Ik heb de code an sich niet in heel veel detail bekeken. Veel testcases ook. Klein puntje bij die assertRaises: je zou evt. nog kunnen checken of de juiste error message gegooid wordt.

**Review by jlunenburg — DISMISSED** [review]

**Review by jlunenburg — COMMENTED** [review]
One more question:
what happens if the execute contains
```python
if hasattr(self.robot, "ssl"):
     self.robot.ssl.do_stuff()
```
? This would be a valid check and might be useful in some cases!

**Comment by MatthijsBurgh** [comment]
This is not yet mature enough

**Pull request closed without merging**
